import type { ToolContext } from "@lovable.dev/mcp-js";

/**
 * Per-instance in-memory rate limiter for MCP tool calls.
 *
 * The Supabase function file for the MCP server is generated by the Vite
 * plugin, so the limit is enforced here — inside the tool handlers — instead of
 * in the request handler. State is per edge instance (best-effort): it stops
 * naive bursts/abuse, it is not a distributed hard guarantee.
 */

const buckets = new Map<string, { count: number; resetAt: number }>();

export interface McpRateLimitOptions {
  /** Max calls allowed per window. */
  limit: number;
  /** Window length in milliseconds. */
  windowMs: number;
}

/** Default: 60 tool calls per minute per caller. */
const DEFAULT: McpRateLimitOptions = { limit: 60, windowMs: 60_000 };

/** Writes are cheaper to abuse — tighter default. */
export const WRITE_LIMIT: McpRateLimitOptions = { limit: 20, windowMs: 60_000 };

function identity(ctx: ToolContext): string {
  try {
    return ctx.getUserId() ?? ctx.getClientId() ?? "anon";
  } catch {
    return "anon";
  }
}

export interface McpRateLimitResult {
  allowed: boolean;
  retryAfterSeconds: number;
}

export function checkMcpRateLimit(
  ctx: ToolContext,
  scope: string,
  opts: McpRateLimitOptions = DEFAULT
): McpRateLimitResult {
  const key = `${scope}:${identity(ctx)}`;
  const now = Date.now();
  const bucket = buckets.get(key);

  if (!bucket || bucket.resetAt <= now) {
    buckets.set(key, { count: 1, resetAt: now + opts.windowMs });
    if (buckets.size > 5000) {
      for (const [k, v] of buckets) if (v.resetAt <= now) buckets.delete(k);
    }
    return { allowed: true, retryAfterSeconds: 0 };
  }

  if (bucket.count >= opts.limit) {
    return {
      allowed: false,
      retryAfterSeconds: Math.max(1, Math.ceil((bucket.resetAt - now) / 1000)),
    };
  }

  bucket.count++;
  return { allowed: true, retryAfterSeconds: 0 };
}

/**
 * Returns an MCP error result when the caller is over the limit, otherwise
 * null. Callers should `return` the result immediately when non-null.
 */
export function mcpRateLimited(
  ctx: ToolContext,
  scope: string,
  opts?: McpRateLimitOptions
): { content: { type: "text"; text: string }[]; isError: true } | null {
  const result = checkMcpRateLimit(ctx, scope, opts);
  if (result.allowed) return null;
  return {
    content: [
      {
        type: "text" as const,
        text: `Rate limit reached for ${scope}. Please retry in ${result.retryAfterSeconds}s.`,
      },
    ],
    isError: true as const,
  };
}
