// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-business-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_business_profile_default = defineTool({
  name: "get_business_profile",
  title: "Get business profile",
  description: "Returns the signed-in user's VyaparSetu business profile(s): name, category, address.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("businesses").select("id,name,category,address,created_at").eq("owner_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { businesses: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-workers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_workers_default = defineTool2({
  name: "list_workers",
  title: "List workers",
  description: "List all workers (employees) for the signed-in user's business with name, role, phone, and daily salary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("workers").select("id,name,role,phone,daily_salary,joined_date").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { workers: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-khata-entries.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_khata_entries_default = defineTool3({
  name: "list_khata_entries",
  title: "List Khata entries",
  description: "List credit/debit ledger (Khata) entries for the signed-in user's business. Optionally filter by customer name.",
  inputSchema: {
    customer_name: z.string().optional().describe("Optional: filter by customer name (partial match)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ customer_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb3(ctx).from("khata_entries").select("id,customer_name,customer_phone,amount,entry_type,description,date").order("date", { ascending: false }).limit(limit ?? 50);
    if (customer_name) q = q.ilike("customer_name", `%${customer_name}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { entries: data ?? [] } };
  }
});

// src/lib/mcp/tools/add-khata-entry.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_khata_entry_default = defineTool4({
  name: "add_khata_entry",
  title: "Add Khata entry",
  description: "Add a credit ('given') or debit ('received') Khata entry for a customer of the signed-in user's business.",
  inputSchema: {
    business_id: z2.string().uuid().describe("Business ID (get from get_business_profile)."),
    customer_name: z2.string().min(1),
    amount: z2.number().positive(),
    entry_type: z2.enum(["given", "received"]).describe("'given' = credit given to customer (they owe you). 'received' = payment received."),
    customer_phone: z2.string().optional(),
    description: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("khata_entries").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Added \u20B9${input.amount} ${input.entry_type} for ${input.customer_name}` }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/list-inventory.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_inventory_default = defineTool5({
  name: "list_inventory",
  title: "List inventory",
  description: "List all inventory items (stock) for the signed-in user's business with quantity, unit, and price.",
  inputSchema: {
    low_stock_only: z3.boolean().optional().describe("If true, only return items at or below their low-stock threshold.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ low_stock_only }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("inventory_items").select("*").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = low_stock_only ? (data ?? []).filter((i) => typeof i.low_stock_threshold === "number" && i.quantity <= i.low_stock_threshold) : data ?? [];
    return { content: [{ type: "text", text: JSON.stringify(items) }], structuredContent: { items } };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_expenses_default = defineTool6({
  name: "list_expenses",
  title: "List expenses",
  description: "List recent expenses for the signed-in user's business.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb6(ctx).from("expenses").select("*").order("date", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { expenses: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "frahzhlxutbfeaororpm";
var mcp_default = defineMcp({
  name: "vyaparsetu-mcp",
  title: "VyaparSetu",
  version: "0.1.0",
  instructions: "Tools for VyaparSetu \u2014 the Indian shopkeeper business manager. Use get_business_profile first to fetch the user's business ID (needed for creating Khata entries). Read workers, khata (credit ledger), inventory, and expenses. Amounts are in INR (\u20B9).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_business_profile_default, list_workers_default, list_khata_entries_default, add_khata_entry_default, list_inventory_default, list_expenses_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
